# Generated by Django 3.0.6 on 2020-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200524_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupform',
            name='blood_group',
            field=models.CharField(default='', max_length=5),
        ),
    ]
