# Generated by Django 3.0.6 on 2020-05-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200524_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='', max_length=15),
        ),
    ]
