# Generated by Django 3.0.6 on 2020-05-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200524_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total_bed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
