# Generated by Django 3.0.6 on 2020-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_appointment_total_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='total_bed',
        ),
        migrations.AddField(
            model_name='signupform',
            name='attendance',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='signupform',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='signupform',
            name='salary',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='signupform',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
