# Generated by Django 3.0.6 on 2020-05-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20200524_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_admitted',
            field=models.BooleanField(default=False),
        ),
    ]
