# Generated by Django 3.0.6 on 2020-05-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20200524_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
