# Generated by Django 3.0.6 on 2020-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20200524_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
