# Generated by Django 3.0.6 on 2020-05-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20200524_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='date',
        ),
    ]
